version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 16
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli@11
  build:
    commands:
        - echo Build started       
        - ng build
  post_build:
    commands:
      - echo "Updating files in the S3 bucket..."
      - aws s3 sync dist/angular/ s3://ojaswini-angular
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
